version: "3.8"
services:
  msa-frontendapp:
    build:
      context: ./msa-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: msa-frontendapp

  visitorapp:
    build:
      context: ./visitor-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: visitorapp

  adminapp:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    container_name: adminapp

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    container_name: nginx
    depends_on:
      - msa-frontendapp
      - visitorapp
      - adminapp
